package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-11-08T20:41:33.556-03:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://ws/", name = "WSInformeAuditoriaBean")
@XmlSeeAlso({ObjectFactory.class})
public interface WSInformeAuditoriaBean {

    @WebMethod
    @RequestWrapper(localName = "agregarInforme", targetNamespace = "http://ws/", className = "ws.AgregarInforme")
    @ResponseWrapper(localName = "agregarInformeResponse", targetNamespace = "http://ws/", className = "ws.AgregarInformeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean agregarInforme(
        @WebParam(name = "arg0", targetNamespace = "")
        ws.LogDTO arg0
    );
}
