package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-11-20T14:05:57.515-03:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://ws/", name = "PedidoFabricaBean")
@XmlSeeAlso({ObjectFactory.class})
public interface PedidoFabricaBean {

    @WebMethod
    @RequestWrapper(localName = "recibirPedido", targetNamespace = "http://ws/", className = "ws.RecibirPedido")
    @ResponseWrapper(localName = "recibirPedidoResponse", targetNamespace = "http://ws/", className = "ws.RecibirPedidoResponse")
    public void recibirPedido(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
