package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-11-20T14:05:57.584-03:00
 * Generated source version: 3.0.5
 * 
 */
@WebServiceClient(name = "PedidoFabricaBeanService", 
                  wsdlLocation = "http://localhost:8080/DepositoApp/PedidoFabricaBean?wsdl",
                  targetNamespace = "http://ws/") 
public class PedidoFabricaBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws/", "PedidoFabricaBeanService");
    public final static QName PedidoFabricaBeanPort = new QName("http://ws/", "PedidoFabricaBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/DepositoApp/PedidoFabricaBean?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PedidoFabricaBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/DepositoApp/PedidoFabricaBean?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PedidoFabricaBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PedidoFabricaBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PedidoFabricaBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PedidoFabricaBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PedidoFabricaBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PedidoFabricaBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns PedidoFabricaBean
     */
    @WebEndpoint(name = "PedidoFabricaBeanPort")
    public PedidoFabricaBean getPedidoFabricaBeanPort() {
        return super.getPort(PedidoFabricaBeanPort, PedidoFabricaBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PedidoFabricaBean
     */
    @WebEndpoint(name = "PedidoFabricaBeanPort")
    public PedidoFabricaBean getPedidoFabricaBeanPort(WebServiceFeature... features) {
        return super.getPort(PedidoFabricaBeanPort, PedidoFabricaBean.class, features);
    }

}
