package wsLM;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-11-01T20:52:31.585-03:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://webService.monitor.com/", name = "WSInformeAuditoriaBean")
@XmlSeeAlso({ObjectFactory.class})
public interface WSInformeAuditoriaBean {

    @WebMethod
    @RequestWrapper(localName = "agregarInforme", targetNamespace = "http://webService.monitor.com/", className = "wsLM.AgregarInforme")
    @ResponseWrapper(localName = "agregarInformeResponse", targetNamespace = "http://webService.monitor.com/", className = "wsLM.AgregarInformeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean agregarInforme(
        @WebParam(name = "arg0", targetNamespace = "")
        wsLM.LogDTO arg0
    );
}
